In [ ]:

#TP_3_BROADCASTING Eléonore Veyron 


import numpy as np
import matplotlib.pyplot as plt

#%matplotlib ipympl

In [7]:

#Echauffement : le broadcasting

a = np.array([1,2,3]) # shape de a = (3)

print(a[:,None], a[:,None].shape)
print(a[None,:], a[None,:].shape)

#1. a[:,None] de shape (3,1), rajoute une dimension "vers la droite" à a
#   a[None,:] de shape (1,3) rajoute une dimension "vers la gauche" à a

#2 Elle sera de la forme (3,3) 
# L'élément [i,j] contient a[:,None][i][1] - a[None,:][1][j]

b=np.array([[1,2,3],[4,5,6]])

#3 b[:,None,:] est de taille (2,1,3) 
# b[:,:,None] est de taille (2,3,1)
# b[:,None,:] - b[:,:,None] va être de taille (2,3,3)
# Avec d = b[:,None,:] - b[:,:,None]
# d[i,j,k] renvoit à b[:,None,:][i][1][k] - b[:,:,None][i][j][1] 
# si on renvoit avec les éléments de b :
#d[i,j,k] = b[i][k]-b[i][j]

[[1]
 [2]
 [3]] (3, 1)
[[1 2 3]] (1, 3)


In [ ]:
# Initialisation aléatoire

# les bornes pour le tirage au sort initial
mass_max = 3.
    
x_min, x_max = -10., 10.
y_min, y_max = -10., 10.

speed_max = 1.

#:tags: [level_basic]

# votre code
#on suppose min_max=0

def init_problem(N):
    """
    retourne un tuple masses, positions, speeds
    de formes resp.   (N,)    (2, N)     (2, N)
    tiré au sort dans les bornes définies ci-dessus
    """
    masses = np.random.uniform(0.1,mass_max, N)
    low=np.array([[x_min],[y_min]])
    high=np.array([[x_max],[y_max]])
    positions = np.random.uniform(low,high,(2,N))
    speeds = np.random.uniform(np.array([-speed_max,speed_max]),np.array([0,speed_max]),(2,N))
    return masses, positions, speeds

masses,positions,speeds=init_problem(10)

In [4]:
#Initialisationreproductible

# for your convenience

def init3():
    # first element is sun-like: heavy, at the center, and no speed
    masses = np.array([3, 1, 1], dtype=float)
    positions = np.array([
        [0, 5, -5], 
        [0, 1, -1]], dtype=float)
    speeds = np.array([
        [0, -1, 1], 
        [0, 0, 0]], dtype=float)
    return masses, positions, speeds


In [20]:
# Les forces 

def forces(masses, positions, G=1.0):
    """
    returns an array of shape (2,  N)
    that contains the force felt by each mass from all the others
    G is the Newton constant and by default is set to 1 
    (we have abstract units anyway)
    """
    r= positions[:,:,None]-positions[:,None,:]
    d= np.linalg.norm(r,axis=0)
    np.fill_diagonal(d,np.inf)
    M= masses[:,None]*masses[None,:]
    coef = G * M
    C=coef[None,:,:]
    F=np.sum(C*r/(d**3),axis=1)
    
    return F

print(forces(init3()[0], init3()[1]))



[[ 0.         -0.12257258  0.12257258]
 [ 0.         -0.02451452  0.02451452]]
